import { Injectable } from '@angular/core';

@Injectable({
	providedIn: 'root'
})
export class LegendService {

	legend_17_19_DFASM1 = [
		"Maladies infectieuses",
		"Médecine du travail et médecine légale",
		"Handicap",
		"Douleurs et soins palliatifs",
		"Génétique appliquée à la médecine",
		"Dermatologie",
		"Endocrinologie-nutrition",
		"Relation de soin",
		"Urgences-réanimation",
		"Rhumatologie",
		"Orthopédie",
		"Gynéco-obstétrique",
		"Urologie",
		"Néphrologie",
		"C2i",
	]
	legend_17_19_DFASM2 = [
		"Pédiatrie",
		"Oncologie",
		"Hématologie",
		"Médecine interne",
		"Néphrologie",
		"Endocrinologie",
		"Gériatrie",
		"Dermatologie",
		"Médecine générale",
		"Psychiatrie",
	]
	legend_17_19_DFGSM2 = [
		"Biologie",
		"Biophysique",
		"Génétique",
		"Immunologie",
		"Anglais médical",
		"EIA Cardio-vasculaire",
		"EIA Respiratoire",
		"EIA Hépato-gastro-entérologie",
		"EIA Neurologie-psychiatrie",
		"EIA Endocrinologie",
		"EIA Néphro-urologie",
		"EIA Locomoteur",
		"Sémiologie",
		"Psychiatrie",
		"Psychiatrie",
	]
	legend_17_19_DFGSM3 = [
		"Bactériologie",
		"Parasitologie",
		"Virologie",
		"ORL",
		"Ophtalmologie",
		"Chirurgie maxillo-faciale",
		"Dermatologie",
		"Pharmacologie",
		"Anatomo-pathologie",
		"Ethique",
		"Relation de soin",
		"Santé publique - LCA",
		"Neurologie",
		"Hépato-gastro-entérologie",
		"Cardiologie",
		"Pneumologie",
	]

	legend_28_29_30_DFASM1 = [
		"EIA Cardio-vasculaire",
		"EIA Respiratoire",
		"EIA Neuro-psychiatrie",
		"EIA Endocrino-métabolisme",
		"EIA Néphro-urologie",
		"EIA Hépato-gastro-entérologie",
		"EIA Locomoteur",
		"Sémiologie",
		"Génétique (DFGSM2)",
		"Biologie",
		"Biophysique",
		"Immunologie",
		"Anglais médical (DFGSM2)",
		"Cardiologie DFGSM3",
		"Pneumologie DFGSM3",
		"HGE DFGSM3",
		"Neurologie DFGSM3",
		"ORL",
		"OPH",
		"Chirurgie maxillo-faciale",
		"Dermatologie",
		"Santé publique LCA",
		"Bactériologie",
		"Virologie",
		"Parasitologie",
		"Anatomo-pathologie",
		"Pharmacologie",
		"Ethique",
		"Relation de soin (binome-jeux de rôle-Premed-Tere-Scoops)",
		"Urgences réanimation",
		"Rhumatologie",
		"Orthopédie",
		"Gynéco-obstétrique",
		"Urologie DFASM1",
		"Néphrologie DFASM1",
		"Endocrinologie",
		"Maladies infectieuses",
		"Handicap et dépendance",
		"Douleurs et soins palliatifs",
		"Médecine légale et travail",
		"Génétique appliquée à la médecine (DFASM1)",
		"C2i",
	]
	legend_28_29_30_DFASM2 = [
		"EIA Cardio-vasculaire",
		"EIA Respiratoire",
		"EIA Neuro-psychiatrie",
		"EIA Endocrino-métabolisme",
		"EIA Néphro-urologie",
		"EIA Hépato-gastro-entérologie",
		"EIA Locomoteur",
		"Sémiologie",
		"Génétique (DFGSM2)",
		"Biologie",
		"Biophysique",
		"Immunologie",
		"Anglais médical (DFGSM2)",
		"Cardiologie DFGSM3",
		"Pneumologie DFGSM3",
		"HGE DFGSM3",
		"Neurologie DFGSM3",
		"ORL",
		"OPH",
		"Chirurgie maxillo-faciale",
		"Dermatologie",
		"Santé publique LCA",
		"Bactériologie",
		"Virologie",
		"Parasitologie",
		"Anatomo-pathologie",
		"Pharmacologie",
		"Ethique",
		"Relation de soin (Binome-jeux de rôle-Premed-Tere-Scoops)",
		"Urgences réanimation",
		"Rhumatologie",
		"Orthopédie",
		"Gynéco-obstétrique",
		"Urologie DFASM1",
		"Néphrologie DFASM1",
		"Endocrinologie",
		"Maladies infectieuses",
		"Handicap et dépendance",
		"Douleurs et soins palliatifs",
		"Médecine légale et travail",
		"Génétique appliquée à la médecine (DFASM1)",
		"Pédiatrie",
		"Hématologie",
		"Oncologie",
		"Médecine interne",
		"Psychiatrie",
		"Gériatrie",
		"Médecine générale",
		"C2i",
	]
	legend_28_29_30_DFGSM2 = [
		"EIA Cardio-vasculaire",
		"EIA Respiratoire",
		"EIA Neuro-psychiatrie",
		"EIA Endocrino-métabolisme",
		"EIA Néphro-urologie",
		"EIA Hépato-gastro-entérologie",
		"EIA Locomoteur",
		"Sémiologie",
		"Génétique",
		"Biologie",
		"Biophysique",
		"Immunologie",
		"Anglais médical",
	]
	legend_28_29_30_DFGSM3 = [
		"EIA Cardio-vasculaire",
		"EIA Respiratoire",
		"EIA Neuro-psychiatrie",
		"EIA Endocrino-métabolisme",
		"EIA Néphro-urologie",
		"EIA Hépato-gastro-entérologie",
		"EIA Locomoteur",
		"Sémiologie",
		"Génétique (DFGSM2)",
		"Biologie",
		"Biophysique",
		"Immunologie",
		"Anglais médical (DFGSM2)",
		"Cardiologie DFGSM3",
		"Pneumologie DFGSM3",
		"HGE DFGSM3",
		"Neurologie DFGSM3",
		"ORL",
		"OPH",
		"Chirurgie maxillo-faciale",
		"Dermatologie",
		"Santé publique LCA",
		"Bactériologie",
		"Virologie",
		"Parasitologie",
		"Anatomo-pathologie",
		"Pharmacologie",
		"Ethique",
		"Relation de soin (Prémed-Tere-Scoops)"
	]
	constructor() { }
}
